config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, skip: :registrations,controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords'
  }

  devise_scope :customer do
  get 'customers/sign_up' => 'public/registrations#new', as: :new_customer_registration
  post 'customers' => 'public/registrations#create', as: :customer_registration
  end
  
  delete 'cart_items/' => 'public/cart_items#alldelete',as: :alldelete
  get 'customers/destroy' => 'public/customers#confirm'
  patch 'customers/destroy' => 'public/customers#destroy'
  post 'orders/confirm' => 'public/orders#confirm',as: :orders_confirm
  get 'orders/complete' => 'public/orders#complete',as: :orders_complete
  root :to => 'public/homes#top'
  get 'about/' => 'public/homes#about'

  scope module: :public do
    resources :items, only: [:index, :show]
    resource :customers, only:[:edit, :show, :update]
    resources :cart_items, only:[:index, :create, :update, :destroy]
    resources :orders, only:[:index, :create, :new, :show]
    resources :addresses, except:[:new, :show]
  end

  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

  namespace :admin do
    resources :order_items, only: [:update]
    resources :orders, only:[:show, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :items, except:[:destroy]
    resources :customers, only:[:index, :show, :edit, :update]
    root :to => 'homes#top', as: 'top'
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def active_for_authentication?
    super && (is_active == true)
  end

  def fullname
    last_name + first_name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::ApplicationController
  def index
    @customers = Customer.all.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    if customer.update(customer_params)
      flash[:success] = "会員情報を更新しました！"
      redirect_to admin_customer_path(params[:id])
    else
      flash[:danger] = "更新に失敗しました"
      @customer = Customer.find(params[:id])
      render :edit

    end
  end

  private
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">

  <div class="row">
    <% flash.each do |key, value| %>
      <p class="alert alert-<%= key %>">
    <%= value %>
      </p>
    <% end %>
  </div>

  <div class="row my-2">
    <h3><%= @customer.fullname %>さんの会員情報編集</h3>
  </div>

    <%= form_with model: @customer,url: admin_customer_path(@customer),local: true do |f| %>
    <div class ="form-group row">
      <%= f.label :customer_id, "会員ID",class: "col-lg-2" %>
      <%= @customer.id %>
    </div>
    <div class ="form-group row">
      <%= f.label :fullname, "氏名",class: "col-lg-2" %>
      <%= f.text_field :last_name,class: "col-lg-3 form-control mr-2" %><%= f.text_field :first_name,class: "col-lg-3 form-control" %>
    </div>
    <div class ="form-group row">
      <%= f.label :kana, "フリガナ",class: "col-lg-2" %>
      <%= f.text_field :last_name_kana,class: "col-lg-3 form-control mr-2" %> <%= f.text_field :first_name_kana,class: "col-lg-3 form-control" %>
    </div>
    <div class ="form-group row">
      <%= f.label :postal_code, "郵便番号",class: "col-lg-2" %>
      <%= f.text_field :postal_code,class: "col-lg-3 form-control" %>
    </div>
    <div class ="form-group row">
      <%= f.label :address, "住所",class: "col-lg-2" %>
      <%= f.text_field :address,class: "col-lg-7 form-control" %>
    </div>
    <div class ="form-group row">
      <%= f.label :ftelephone_number, "電話番号",class: "col-lg-2" %>
      <%= f.text_field :telephone_number,class: "col-lg-3 form-control" %>
    </div>
    <div class ="form-group row">
      <%= f.label :email, "メールアドレス",class: "col-lg-2" %>
      <%= f.email_field :email,class: "col-lg-3 form-control" %>
    </div>
     <div class ="form-group row">
      <%= f.label :is_active, "会員ステータス",class: "col-lg-2" %>
      <%= f.radio_button :is_active,true, checked: true %>有効 <%= f.radio_button :is_active,false %>退会
    </div>
      <%= f.submit "変更を保存",class: "btn btn-success" %>
      <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row my-2">
    <h3>会員一覧</h3>
  </div>
  <table class="table">
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= link_to admin_customer_path(customer) do %>
          <%= customer.fullname %>
          <% end %>
      </td>
      <td><%= customer.email %></td>
      <% if customer.is_active == true %>
      <td class ="text-success">有効</td>
      <% else %>
      <td class="text-secondary">退会</td>
      <% end %>
    </tr>
    <% end %>
  </table>
  <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row my-2">
    <h3><%= @customer.fullname %>さんの会員詳細</h3>
  </div>

  <div class="row">
    <div class="col">
      <table class="table">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.last_name %> <%= @customer.first_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
        <% if @customer.is_active == true %>
        <td class="text-success">有効</td>
        <% else %>
        <td class="text-secondary">退会</td>
        <% end %>
        </tr>
      </table>
      <%= link_to "編集する",edit_admin_customer_path(@customer) ,class: "btn btn-success"%>
      <%= link_to "注文履歴一覧を見る",admin_top_path,class: "btn btn-primary"%>
    </div>
</div>