config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, skip: :registrations,controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords'
  }

  devise_scope :customer do
  get 'customers/sign_up' => 'public/registrations#new', as: :new_customer_registration
  post 'customers' => 'public/registrations#create', as: :customer_registration
  end
  
  delete 'cart_items/' => 'public/cart_items#alldelete',as: :alldelete
  get 'customers/destroy' => 'public/customers#confirm'
  patch 'customers/destroy' => 'public/customers#destroy'
  post 'orders/confirm' => 'public/orders#confirm',as: :orders_confirm
  get 'orders/complete' => 'public/orders#complete',as: :orders_complete
  root :to => 'public/homes#top'
  get 'about/' => 'public/homes#about'

  scope module: :public do
    resources :items, only: [:index, :show]
    resource :customers, only:[:edit, :show, :update]
    resources :cart_items, only:[:index, :create, :update, :destroy]
    resources :orders, only:[:index, :create, :new, :show]
    resources :addresses, except:[:new, :show]
  end

  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

  namespace :admin do
    resources :order_items, only: [:update]
    resources :orders, only:[:show, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :items, except:[:destroy]
    resources :customers, only:[:index, :show, :edit, :update]
    root :to => 'homes#top', as: 'top'
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :addresses, presence: true

  def pcode_address_name
    "〒" + self.postal_code + self.addresses + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :registerable,:recoverable, 
         :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true

  def sub_total
    item.taxprice.to_i * amount.to_i
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def active_for_authentication?
    super && (is_active == true)
  end

  def fullname
    last_name + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  belongs_to :genre
  has_many :order_items
  attachment :image
  
  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def taxprice
    tax = 1.1
    (price * tax).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method:{
      クレジットカード: 0,
      銀行振込: 1
  }

  enum status:{
      入金待ち: 0,
      入金確認: 1,
      製作中: 2,
      発送準備中: 3,
      発送済み: 4
  }
  
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

 belongs_to :customer
 has_many :order_items,dependent: :destroy

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  enum making_status:{
      製作不可: 0,
      製作待ち: 1,
      製作中: 2,
      製作完了: 3
  }

  belongs_to :item
  belongs_to :order

  def sub_total
    price * amount
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::ApplicationController

  def top
    path = Rails.application.routes.recognize_path(request.referer)
    #byebug
    if path[:controller] == "admin/customers" && path[:action] == "show"
      @orders = Order.where(customer_id: path[:id]).page(params[:page]).reverse_order
    else
      @orders = Order.all.page(params[:page]).reverse_order
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::ApplicationController
  def index
    @items = Item.all.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    item = Item.new(item_params)
    if item.save
      flash[:success] = "商品の登録に成功しました！"
      redirect_to admin_item_path(item)
    else
      flash[:danger] = "商品の登録に失敗しました。内容を確認してください"
      @item = Item.new
      @genres = Genre.all
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      flash[:success] = "内容が更新されました！"
      redirect_to admin_item_path(item.id)
    else
      flash[:danger] = "更新に失敗しました。内容を確認してください"
      @item = Item.find(params[:id])
      @genres = Genre.all
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :is_active,:genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  def show
    @order = Order.find(params[:id])
    @sum = 0
    @order.order_items.each do |order_item|
      @sum += order_item.sub_total
    end
  end

  def update
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger

end

app/controllers/z/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/z/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/z/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row my-2">
    <h3>注文履歴詳細</h3>
  </div>

  <div class="row">
    <table class="table">
      <tr>
        <th>購入者</th>
        <td><%= link_to '@order.customer.name', admin_customer_path(@order)  %></td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td><%= @order.address %></td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= @order.payment_method %></td>
      </tr>
      <tr>
        <th>注文ステータス</th>
        <td><%= %></td>
        <td><%= link_to "更新", admin_order_path, class: "btn btn-success" %></td>
      </tr>
    </table>
  </div>

  <div class="row">
    <div class="col-lg-10">
      <table class="table">
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
        <% @orders.each do |order| %>
        <tr>
          <%= order.order_item.item.name %>
          <%= order.order_item.price %>
          <%= order.order_item.amount %>
          <%= order.order_item.subtotal %>
          <%=%>
        <% end %>
        <%= link_to "更新", admin_order_ite_path, class: "btn-btn-success" %>
        </tr>

      </table>
    </div>
    <div class="col-lg-2">
      <table>
        <tr>
          <th>商品合計</th>
          <td><%= @order.subtotal.sum %> </td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.shipping_cost %></td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= @order.total_payment %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row my-2">
    <h3>注文履歴詳細</h3>
  </div>

  <div class="row">
    <table class="table">
      <tr>
        <th>購入者</th>
        <td><%= link_to admin_customer_path(@order.customer_id) do %>
            <%= @order.customer.fullname %>
            <% end %>
        </td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td><%= @order.address %></td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= @order.payment_method %></td>
      </tr>
      <tr>
        <th>注文ステータス</th>
        <td><%= %></td>
        <!--<td><= link_to "更新", admin_order_path, class: "btn btn-success" %></td>-->
      </tr>
    </table>
  </div>

  <div class="row">
    <div class="col-lg-10">
      <table class="table">
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
        <tr>
          <% @order.order_items.each do |order_item| %>
          <td><%= order_item.item.name %></td>
          <td><%= order_item.price %></td>
          <td><%= order_item.amount %></td>
          <td><%= order_item.sub_total %></td>
          <td></td>
        <% end %>
        <!--<= link_to "更新", admin_order_ite_path, class: "btn-btn-success" %>-->
        </tr>

      </table>
    </div>
    <div class="col-lg-2">
      <table>
        <tr>
          <th>商品合計</th>
          <td><%= @sum.to_s(:delimited) %> </td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= (@order.shipping_cost).to_s(:delimited) %></td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= (@order.total_payment).to_s(:delimited) %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>