config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, skip: :registrations,controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords'
  }

  devise_scope :customer do
  get 'customers/sign_up' => 'public/registrations#new', as: :new_customer_registration
  post 'customers' => 'public/registrations#create', as: :customer_registration
  end
  
  delete 'cart_items/' => 'public/cart_items#alldelete',as: :alldelete
  get 'customers/destroy' => 'public/customers#confirm'
  patch 'customers/destroy' => 'public/customers#destroy'
  post 'orders/confirm' => 'public/orders#confirm',as: :orders_confirm
  get 'orders/complete' => 'public/orders#complete',as: :orders_complete
  root :to => 'public/homes#top'
  get 'about/' => 'public/homes#about'

  scope module: :public do
    resources :items, only: [:index, :show]
    resource :customers, only:[:edit, :show, :update]
    resources :cart_items, only:[:index, :create, :update, :destroy]
    resources :orders, only:[:index, :create, :new, :show]
    resources :addresses, except:[:new, :show]
  end

  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

  namespace :admin do
    resources :order_items, only: [:update]
    resources :orders, only:[:show, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :items, except:[:destroy]
    resources :customers, only:[:index, :show, :edit, :update]
    root :to => 'homes#top', as: 'top'
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :addresses, presence: true

  def pcode_address_name
    "〒" + self.postal_code + self.addresses + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :registerable,:recoverable, 
         :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true

  def sub_total
    item.taxprice.to_i * amount.to_i
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def active_for_authentication?
    super && (is_active == true)
  end

  def fullname
    last_name + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  belongs_to :genre
  has_many :order_items
  attachment :image
  
  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def taxprice
    tax = 1.1
    (price * tax).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method:{
      クレジットカード: 0,
      銀行振込: 1
  }

  enum status:{
      入金待ち: 0,
      入金確認: 1,
      製作中: 2,
      発送準備中: 3,
      発送済み: 4
  }
  
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

 belongs_to :customer
 has_many :order_items,dependent: :destroy

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  enum making_status:{
      製作不可: 0,
      製作待ち: 1,
      製作中: 2,
      製作完了: 3
  }

  belongs_to :item
  belongs_to :order

  def sub_total
    price * amount
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::ApplicationController

  def top
    path = Rails.application.routes.recognize_path(request.referer)
    #byebug
    if path[:controller] == "admin/customers" && path[:action] == "show"
      @orders = Order.where(customer_id: path[:id]).page(params[:page]).reverse_order
    else
      @orders = Order.all.page(params[:page]).reverse_order
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger

end

app/controllers/z/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/z/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/442d465ed4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark navbar-fixed-top navbar-expand-lg">
      <div class="navbar-header">
        <%= link_to root_path do %>
          <i class="navbar-brand fas fa-birthday-cake">ながのCAKE</i>
        <% end %>
      </div>

      <% if admin_signed_in? %>
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item"><%= link_to "商品一覧", admin_items_path ,class: "btn btn-outline-secondary mr-4"%></li>
        <li class="nav-item"><%= link_to "会員一覧", admin_customers_path ,class: "btn btn-outline-secondary mr-4"%></li>
        <li class="nav-item"><%= link_to "注文履歴一覧", admin_top_path ,class: "btn btn-outline-secondary mr-4" %></li>
        <li class="nav-item"><%= link_to "ジャンル一覧", admin_genres_path ,class: "btn btn-outline-secondary mr-4" %></li>
        <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete ,class: "btn btn-outline-secondary mr-4"%></li>
         <form class="navbar-form navbar-right" role="search">
          <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
          </div>
        </form>
      </ul>
      <% else %>
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item" ><%= link_to "About" , about_path, class: "btn btn-outline-secondary mr-4" %></li>
        <li class="nav-item"><%= link_to "商品一覧",items_path, class: "btn btn-outline-secondary mr-4"%></li>
        <li class="nav-item"><%= link_to "新規登録",new_customer_registration_path ,class: "btn btn-outline-secondary mr-4"%></li>
        <li class="nav-item"><%= link_to "ログイン",new_admin_session_path, class: "btn btn-outline-secondary mr-4"%></li>
      </ul>
      <% end %>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/442d465ed4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark navbar-fixed-top navbar-expand-lg">
      <div class="navbar-header">
        <%= link_to root_path do %>
          <i class="navbar-brand fas fa-birthday-cake">ながのCAKE</i>
        <% end %>
      </div>
      <% if customer_signed_in? %>
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item"><%= link_to "マイページ", customers_path ,class: "btn btn-outline-secondary mr-4"%></li>
        <li class="nav-item"><%= link_to "商品一覧", items_path ,class: "btn btn-outline-secondary mr-4"%></li>
        <li class="nav-item"><%= link_to "カート", cart_items_path ,class: "btn btn-outline-secondary mr-4" %></li>
        <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete ,class: "btn btn-outline-secondary mr-4"%></li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item" ><%= link_to "About" , about_path, class: "btn btn-outline-secondary mr-4" %></li>
        <li class="nav-item"><%= link_to "商品一覧",items_path, class: "btn btn-outline-secondary mr-4"%></li>
        <li class="nav-item"><%= link_to "新規登録",new_customer_registration_path ,class: "btn btn-outline-secondary mr-4"%></li>
        <li class="nav-item"><%= link_to "ログイン",new_customer_session_path, class: "btn btn-outline-secondary mr-4"%></li>
      </ul>
      <% end %>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/z/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/z/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>